trigger:
- master

pool:
  vmImage: 'macOS-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- checkout: self
  submodules: true

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'coverlet/*.sln'
    
- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    platform: 'Any CPU'
    configuration: 'Release'
    clean: true
    restoreNugetPackages: true
