trigger:
- "*"

pool:
  vmImage: 'macOS-latest'

variables:
  solution: 'VSMac-CodeCoverage/VSMac-CodeCoverage.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:

  - job: Build
    steps:
      - checkout: self
        submodules: true
      - task: NuGetCommand@2
        inputs:
          command: 'restore'
          restoreSolution: '$(solution)'
      - task: MSBuild@1
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          clean: true
          restoreNugetPackages: true

  - job: Release
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'))
    steps:
      - script: "echo TESTING"
