trigger:
- master

pool:
  vmImage: 'macOS-latest'

variables:
  solution: 'VSMac-CodeCoverage/VSMac-CodeCoverage.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- checkout: self
  submodules: true
    
- task: MSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true
    restoreNugetPackages: true
